%% Import data from QIDS spreadsheet
%
% Auto-generated by MATLAB on 31-May-2022 23:27:13

%% Set source location

sourcefolder = ["/Users/marthanarinemrihavenith/Desktop/Manuscripts/Submitted/2023-10 Breathwork CO2/Source Excels/QIDS.xlsx"];

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 3);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:C34";

% Specify column names and types
opts.VariableNames = ["Pre1week", "Post1week", "Post3months"];
opts.SelectedVariableNames = ["Pre1week", "Post1week", "Post3months"];
opts.VariableTypes = ["double", "double", "double"];

% Import the data
QIDS = readtable(sourcefolder, opts, "UseExcel", false);
QIDSmatrix = [QIDS.Pre1week QIDS.Post1week]; % QIDS.Post3months];
Nanrows = find(isnan(mean(QIDSmatrix'))==1);
QIDSmatrix(Nanrows,:)= NaN;
QIDSnames = {'1 week pre'; '1 week post'};

%% Clear temporary variables
clear opts Nanrows QIDS