%% Import data from Subject Info spreadsheet

% Auto-generated by MATLAB on 13-Feb-2024 11:26:42

%% Set source location

sourcefolder = ["/Users/marthanarinemrihavenith/Desktop/Manuscripts/Submitted/2023-10 Breathwork CO2/Source Excels/SubjectInfo.xlsx"];

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 6);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:F62";

% Specify column names and types
opts.VariableNames = ["ID", "age", "gender", "work_status", "holcon", "breath"];
opts.SelectedVariableNames = ["ID", "age", "gender", "work_status", "holcon", "breath"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double"];
opts = setvaropts(opts, 1, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 1, "EmptyFieldRule", "auto");

% Import the data
SubjectInfo = readtable(sourcefolder, opts, "UseExcel", false);


%% Clear temporary variables
clear opts