%% Import data from WEMBWS spreadsheet
%
% Auto-generated by MATLAB on 02-Jun-2022 00:50:32

%% Set source location

sourcefolder = ["/Users/marthanarinemrihavenith/Desktop/Manuscripts/Submitted/2023-10 Breathwork CO2/Source Excels/WEMBWS.xlsx"];

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 5);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:E34";

% Specify column names and types
opts.VariableNames = ["Pre1week", "Post1week", "Post3months","holcon","breath"];
opts.SelectedVariableNames = ["Pre1week", "Post1week", "Post3months","holcon","breath"];
opts.VariableTypes = ["double", "double", "double", "double", "double"];

% Import the data
WEMBWS = readtable(sourcefolder, opts, "UseExcel", false);
WEMBWSmatrix = [WEMBWS.Pre1week WEMBWS.Post1week]; % WEMBWS.Post3months];

Nanrows = find(isnan(mean(WEMBWSmatrix'))==1);
WEMBWSmatrix(Nanrows,:)= NaN;
WEMBWSnames = {'1 week pre'; '1 week post'};

holconSURVEYvector = WEMBWS.holcon;
breathSURVEYvector = WEMBWS.breath+1;
 

%% Clear temporary variables
clear opts Nanrows WEMBWS